# Generated by Django 5.2 on 2025-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mood_rating', models.IntegerField(blank=True, choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Neutro'), (4, 'Bom'), (5, 'Excelente')], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Atividade Diária (Humor)',
                'verbose_name_plural': 'Atividades Diárias (Humor)',
                'ordering': ['date'],
            },
        ),
    ]
