# Generated by Django 5.2 on 2025-06-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mood_rating', models.IntegerField(blank=True, choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Neutro'), (4, 'Bom'), (5, 'Excelente')], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Atividade Diária (Humor)',
                'verbose_name_plural': 'Atividades Diárias (Humor)',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tarefa Diária a Rastrear',
                'verbose_name_plural': 'Tarefas Diárias a Rastrear',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('livro', 'Livro'), ('filme', 'Filme'), ('serie', 'Série')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Mídia Consumida',
                'verbose_name_plural': 'Itens de Mídia Consumida',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='atividades.dailytaskitem')),
            ],
            options={
                'verbose_name': 'Conclusão de Tarefa Diária',
                'verbose_name_plural': 'Conclusões de Tarefas Diárias',
                'ordering': ['date', 'task__name'],
                'unique_together': {('task', 'date')},
            },
        ),
    ]
