# Generated by Django 4.2.14 on 2024-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dia',
            name='avaliacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dia',
            name='destaque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
