# Generated by Django 4.2.14 on 2024-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_dia_numero_alter_dia_avaliacao_alter_dia_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoHabitual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('atividade', models.CharField(max_length=100)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dia',
            name='destaque',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='numero',
        ),
        migrations.AlterField(
            model_name='dia',
            name='avaliacao',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
