# Generated by Django 5.2 on 2025-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_progressohabitual_remove_dia_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Atividade Diária',
                'verbose_name_plural': 'Atividades Diárias',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='ProgressoHabitual',
        ),
    ]
